import { Client } from "../Client";
import { InvoiceAddress } from "../address/InvoiceAddress";
import { File } from "../File";
import { CustomerAddress } from "../address/CustomerAddress";
import { OrderAddOn } from "./OrderAddOn";
import { Package } from "../Package";
import { Price } from "../Price";

export interface Order {
  /* only required for requests */
  ExtOrderId?: string;
  OrderNumber?: string;
  HWB?: string;
  Reference1?: string;
  Reference2?: string;
  InfoInvoice?: string;
  SetState5?: string;
  Client: Client;
  Currency: string;
  CostCenter?: string;
  Distance?: string;
  NumberOfPackages?: string;
  Weight?: string;
  DimWeight: string;
  ClientDimWeight: string;
  Content?: string;
  DocsOnly?: string;
  Value?: string;
  CurrencyValue?: string;
  InsuredValue?: string;
  CurrencyInsuredValue?: string;
  CustomsValue?: string;
  CurrencyCustomsValue?: string;
  OrderToDisp?: string;
  InvoiceRecNo?: string;
  ExtWebhookUrl?: string;
  MasterReferenceNumber?: string;
  UNNumbers1?: string;
  UNNumbers2?: string;
  Monitoring?: string;
  MailDoc6?: string;
  Tour?: string;
  Duration: string;
  MailDoc6Emails?: string;
  InvoiceAddress?: InvoiceAddress;
  TypeOfTransport?: string;
  ProductClient: string;
  ProductClientScreenText?: string;
  ProductClientLongText?: string;
  ProductCarrier: string;
  ProductCarrierScreenText?: string;
  ProductCarrierLongText?: string;
  Carrier?: string;
  ProductCourier?: string;
  ProductCourierScreenText?: string;
  ProductCourierLongText?: string;
  ProductForDevice?: string;
  Courier?: string;
  CourierDevice?: string;
  CourierCompany?: string;
  CourierFirstName?: string;
  CourierLastName?: string;
  CourierPhone?: string;
  CourierEmail?: string;
  CarType?: string;
  InfoDispo?: string;
  InfoCourier?: string;
  InfoRunSheet?: string;
  Cash?: string;
  NotPrepaid?: string;
  CODGoods?: string;
  CODGoodsC?: string;
  CODTransportation?: string;
  CODTransportationC?: string;
  CODType?: string;
  DeliveryParkingPermit?: string;
  DeliveryDepositLocation?: string;
  DeliveryAccessCode?: string;
  /** First entry must have `Type` = '1' and last entry `Type` = '2' */
  Address: Array<CustomerAddress>;
  TrackingLink?: string;
  Package: Array<Package>;
  LabelFormat?: string;
  Label?: string;
  Neutral?: string;
  DeoSendDepot?: string;
  File?: File;
  AddOn: Array<OrderAddOn>;
  AddOnCarrier: Array<OrderAddOn>;
  AddOnCourier: Array<OrderAddOn>;
  Price?: Price;
  Photo: Array<{
    UUID?: string;
    Base64?: string;
  }>;
}
